packages:
  - apps/*
  - packages/*
  - shared/*
  - shared/configs/*

catalog:
  lucide-react: ^0.518.0

catalogs:
  types:
    '@types/node': ^24.0.3
  typescript:
    typescript: ^5.8.3
    typescript-plugin-css-modules: ^5.1.0
  react:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    react: ^19.1.0
    react-dom: ^19.1.0
  storybook:
    storybook: ^9.0.12
    '@storybook/react-vite': ^9.0.12
  playwright:
    playwright: ^1.53.1
    '@playwright/test': ^1.53.1
    '@playwright/experimental-ct-react': ^1.53.1
  vite:
    '@tailwindcss/vite': ^4.1.10
    '@vitejs/plugin-react-swc': ^3.10.2
    vite: ^6.3.5
    vite-tsconfig-paths: ^5.1.4
  vitest:
    vitest: ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/coverage-istanbul': ^3.2.4
    '@vitest/browser': ^3.2.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - lefthook
  - sharp
